using System;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Credfeto.SourceGeneration.Helpers.Builders;

public sealed class CodeBuilder
{
    private readonly StringBuilder _stringBuilder = new(16384);

    private int _indent;

    private SourceText? CachedText { get; set; }

    public SourceText Text =>
        this.CachedText ??= SourceText.From(
            this._stringBuilder.ToString(),
            encoding: Encoding.UTF8,
            checksumAlgorithm: SourceHashAlgorithm.Sha256
        );

    public CodeBuilder AppendFileHeader()
    {
        return this.AppendLine("//------------------------------------------------------------------------------")
            .AppendLine("// <auto-generated>")
            .AppendLine("// This code was generated by a tool.")
            .AppendLine("// Runtime Version: Current")
            .AppendLine("//")
            .AppendLine("// Changes to this file may cause incorrect behavior and will be lost if")
            .AppendLine("// the code is regenerated.")
            .AppendLine("// </auto-generated>")
            .AppendLine("//------------------------------------------------------------------------------")
            .AppendBlankLine();
    }

    public CodeBuilder AppendBlankLine()
    {
        this._stringBuilder.AppendLine();
        this.CachedText = null;

        return this;
    }

    public CodeBuilder AppendGeneratedCodeAttribute(string tool, string version)
    {
        return this.AppendLine($"[GeneratedCode(tool: \"{tool}\", version: \"{version}\")]");
    }

    public CodeBuilder AppendLine(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return this.AppendBlankLine();
        }

        this._stringBuilder.Append(value: ' ', repeatCount: 4 * this._indent).AppendLine(text);
        this.CachedText = null;

        return this;
    }

    public IDisposable StartBlock(string text)
    {
        return this.StartBlock(text: text, start: "{", end: "}");
    }

    public IDisposable StartBlock(string text, string start, string end)
    {
        this.AppendLine(text);

        return new Indent(this, start: start, end: end);
    }

    private sealed class Indent : IDisposable
    {
        private readonly CodeBuilder _builder;
        private readonly string _end;

        public Indent(CodeBuilder builder, string start, string end)
        {
            this._builder = builder;
            this._end = end;

            this._builder.AppendLine(start);
            ++this._builder._indent;
        }

        public void Dispose()
        {
            --this._builder._indent;
            this._builder.AppendLine(this._end);
        }
    }
}
